### ISSUE TITLE
Cant respond to alarm or use camera without unlocking NFC phone app

### ISSUE THREAD

**Issue by jasok2** [mclear/Android_NFC_Ring_Unlock#32]
on the normal unlock screen I can usually respond to an alarm and use the camera without logging in, however I cannot do this without unlocking the NFC app.

which is particularly annoying when trying to snooze an alarm in the morning.

**Comment by northan77** [comment]
I tried this feature, I have to say that finding that sweet spot when your alarm is going off first thing is not cool. Can a feature like the phone call manager be implemented?

**Comment by r2DoesInc** [comment]
The issue is that there is no one "alarm" app. each manufacturer uses a different one, and a user could have one of a million other installed. there is no one action to listen to. i have tried implementing this in the past, but until android  revamps their alarm manager this is not goign to be possible.
