### ISSUE TITLE
Does not work with google two-factor authentication

### ISSUE THREAD

**Issue by pmdhazy** [mclear/Android_NFC_Ring_Unlock#7]
I thought I set up an NFC tag but when try it says Invalid Credentials.
Sliding unlock icon to the left for the keyboard prompts for the gmail email and password but fails since I have 2 factor authentication setup and the app does not appear to fallback to the web login screen like other google apps to handle this.

Also, how do I reset the ring unlock so I can startover and get in again? :-(

Edited to add: Nexus 5 phone running Android 4.4.2

**Comment by r2DoesInc** [comment]
To factor must be turned off for that feature to work.

**Comment by TheCustomCave** [comment]
Is there any way to remove that entirely then as there's no way I'm going to remove my 2 factor auth on my Google account and it seems silly to then have a redundant system to be the standard fall-back. It would be nice to be able to pick the fall-back in the same way the keypad doesn't show if you turn that feature off.

**Comment by r2DoesInc** [comment]
Gmail cannot be turned off as a fallback, and there is no "standard"
fallback. You choose your fallback when you swipe. If you want a different
fallback method, setup the pin unlock and swipe right rather than left.

**Comment by TheCustomCave** [comment]
That's what I was getting at. If the gmail fallback isn't useful (as it's not to anyone with 2 factor auth) then it would be nice to be able to switch that off completely as you can with the pin.

**Comment by TheCustomCave** [comment]
I should actually point out that mine IS actually working with just the gmail address and password and I do have 2 factor auth enabled.

**Comment by r2DoesInc** [comment]
Then apparently it does work. I don't have two factor auth in any devices,
and I'm not entirely sure how it works. I assumed from the little I knew
about how it worked that it would not function. I may have been completely
incorrect.

**Comment by TheCustomCave** [comment]
Well it works on mine but doesn't seem to work on OP's device.

There's a couple of different methods for it so it may be down to that.

**Comment by r2DoesInc** [comment]
I've heard users mention it not working in the past, so I'm relatively
surprised you mentioned you had it working.

There's no need for a way to disable that functionality, especially since
its not something that I would be able to detect and handle automatically,
it would have to be an extra check box with the option to hide it, which is
unnecessary IMO since the fallback option isn't forced upon any user and
the ui to get to it is quite subtle as well.

**Comment by pmdhazy** [comment]
For anyone else with this problem, de-installing the app and then re-installing it gets back to the settings and you need to select Application Security Settings and then Manage application passwords and set a PIN up. Sliding right from the lock screen then lets you enter PIN to get back in. Obviously less secure but very useful when first testing....

**Comment by JohnMcLear** [comment]
Worth popping in the Wiki? https://github.com/mclear/Android_NFC_Ring_Unlock/wiki

**Comment by xxv** [comment]
The UI to get to the gmail unlock is not subtle; it's a big red thing and in fact the only active component on the screen. 

Having an option to disable this gmail unlock fallback would be an actual security boost, unlike some of the other options (such as lockscreen widget disabling) which don't really provide much security benefit. The main reason disabling the gmail unlock would be valuable is due to bugs in the unlock app which flash whatever's on the screen under the lockscreen briefly.

**Comment by r2DoesInc** [comment]
no longer relevant.
